### ISSUE TITLE
Creating new file

### ISSUE THREAD

**Issue by koendv** [robert-hh/Micropython-Editor#10]
Hi. Thanks for pye; I like it.

One problem: when creating a new file, I get an AttributeError 'module' object has no attribute is_dir.

**Comment by robert-hh** [comment]
Thanks. I'll look for it. Which platform are you using?

**Comment by robert-hh** [comment]
Ok, Found the culprit as an regression error. WIll fix that in a minute. That fix consists of adding:

self.is_dir = False

to the method __init__() or as the first statement in get_file()

**Comment by koendv** [comment]
> Thanks. I'll look for it. Which platform are you using?
MicroPython v1.12-691-g20e7f4d6e-dirty on 2020-08-14; stlink3mini with stm32f723iek

**Comment by koendv** [comment]
> Ok, Found the culprit as an regression error. WIll fix that in a minute.
Great. Tested, works again. A pleasure.
