### ISSUE TITLE
not an issue kind of cool though 

### ISSUE THREAD

**Issue by ukscone** [robert-hh/Micropython-Editor#12]
had/have a few problems getting it working but managed in the end (needed to rebuild rp2 micropython port to include ure for a start) but editor seems to work quite well in chrome when chrome is being used to access the repl
![Screenshot 2021-02-09 6 47 09 PM](https://user-images.githubusercontent.com/3171454/107444044-e708f880-6b07-11eb-9aa8-dc40135393d6.png)

**Comment by robert-hh** [comment]
Thanks. The module ure is meanwhile included in the standard builds, as well as other modules. You can safely use the daily build of micropython. They are usually as stable as the "standard" builds.
I never tried chrome for the access. I usually use picocom or tio.

**Comment by ukscone** [comment]
redid my uf2 to the "official" one rather than my hacked vid/pid cuz chromebook one and all looks good. i'm using a hacked about google serial api example as the terminal in browser

https://github.com/GoogleChromeLabs/serial-terminal
https://googlechromelabs.github.io/serial-terminal/

with the serial-terminal and your editor it means pretty much everything micropython-y on the pico can be done via the browser

**Comment by robert-hh** [comment]
I found beagle term which works well too. Also a Chrome app. On windows it's the best terminal emulator I have seen so far.

**Comment by ukscone** [comment]
yes I like beagleterm and use/used it a lot but slowly weaning myself off it as it'll stop working soon (eventually) as it's an "app" not an extension and google is phasing out app support (sometime this year I believe) to replace it with pwa's and extensions only
