### ISSUE TITLE
Help request: UART input and display output

### ISSUE THREAD

**Issue by kmatch98** [robert-hh/Micropython-Editor#2]
Can you give me some guidance on what modifications to the pyEditor code is required for accepting UART Inputs and also for displaying on an attached display?

Right now all inputs and outputs are run off the serial console. 

Why I’m asking: I have a USB Host mode running on a coprocessor and sending keyboard codes to the main processor via UART. On the main processor I have a small display (240x240 pixels) showing the REPL console.  I want to edit files using the attached USB keyboard through the UART and see it on this display.  I want to be able to do this without requiring attachment to a computer via Serial. Basically, I want to make this a stand-alone CircuitPython computer. I’ll appreciate any guidance on how to update your code to support this standalone concept.

**Comment by robert-hh** [comment]
The input part is easy. That existed in earlier versions of the repository. If you checkout for instance 2.3 (551b1f70ef0562081525eb60f43412a22fe5d31d), you see that there is a selection between sys.stdin and UART in init_tty(). That should be easy to adapt. Using a LCD as output is more tricky, since it assumes a VT100 console. But most of the output is done though the function display(). I think the only place where not is in get_screen_size(), which probes the display for it's size. For a fixed display you can simple return the values without probing.

**Comment by kmatch98** [comment]
Right now, the CircuitPython terminal window doesn't handle all the VT100 commands used in the py-editor.  I've been able to modify the output to route to a connected display using the terminalio.Terminal() module, but not all functions work properly for your editor due to the incomplete set of VT100 commands that are currently implemented.

https://github.com/adafruit/circuitpython/blob/master/shared-module/terminalio/Terminal.c

**Comment by robert-hh** [comment]
Actually this code only handles clear-eol and go back by n steps. The editor requires at least
- clear-eol ESC[K
- set cursor ESC[ yy;xxH
- some kind of highlight ESC[xxm
- scroll up ESC[M
You can omit the scrolling code, if you just make the functions scroll_region, scrool_up and scroll_down dummy ones. Then the screen is simply redrawn, if required.
But Set-Cursor is essential. If you can set the cursor by other means, change the function goto() accordingly. The function get_screen_size is called during refresh and just returns a tuple with the (height,width) size of the screen. It uses a VT100 code, but for a fixed display you can simply return these values.

**Comment by kmatch98** [comment]
Thanks for the timely and  astute directions on where focus.  I honed in on a few of the ANSI control sequences that aren’t handled in the current MicroPython Terminal. I opened an [issue](https://github.com/adafruit/circuitpython/issues/2839) with the CircuitPython team but I understand they are trying to keep the code lean.

I’m working through a couple of issues that are slowing me down for debugging, I’ll fight through that and then try to get a couple of the required basic commands working. I’ve got the “wr” command showing some text (garbled) on the display screen so that is progress!

<snip>
From Robert-hh:
Actually this code only handles clear-eol and go back by n steps. The editor requires at least

clear-eol ESC[K
set cursor ESC[ yy;xxH
some kind of highlight ESC[xxm
scroll up ESC[M
You can omit the scrolling code, if you just make the functions scroll_region, scrool_up and scroll_down dummy ones. Then the screen is simply redrawn, if required.
But Set-Cursor is essential. If you can set the cursor by other means, change the function goto() accordingly. The function get_screen_size is called during refresh and just returns a tuple with the (height,width) size of the screen. It uses a VT100 code, but for a fixed display you can simply return these values.

**Comment by kmatch98** [comment]
Robert-hh,

I made some good progress last night on the simple terminal for CircuitPython. Here’s a status update:

https://youtu.be/Kp8AaYRiiVU

Thanks again for your help. Once I connect it to your editor I will ask for your suggestions on how to proceed.  

-Kevin

**Comment by kmatch98** [comment]
I successfully edited my first file yesterday, via UART input and display output. Let me squash a few bugs related to the status line updates. 

Still missing is the hilite capability. This is going to take a refiguring of the display strategy so I think I’ll forgo this for now. Also, adding it will probably degrade scrolling capability. I have put highlight on hold but I’ll make a few notes later about some ideas about how to implement it.

**Comment by robert-hh** [comment]
If the terminal supports two fonts, you could switch between the two. The seconds font yould be an inverted one, or underlined, or ...

**Comment by kmatch98** [comment]
Great suggestion. I think the easiest solution is to make an inverted version of my existing font. I should be able to do that in the code.

**Comment by kmatch98** [comment]
robert-hh, thanks for your support on this editor, I works great and has a lot of functions!  I was able to get this working with a keyboard connected through a USB hot controller and output to a connected display.  You can see the project here:

https://hackaday.io/project/171269-cyberdck-a-circuitpython-anatidae

I’ll clean up my code and then upload it here. I’ve never uploaded to github before so please bear with me while I figure it out.

**Comment by robert-hh** [comment]
That one looks impressive. There has been a question a while ago by another forum member, who wanted to implement a similar project for a simple operator terminal. But I never heard again from that project.

**Comment by kmatch98** [comment]
I uploaded the CircuitPython simpleTerminal class over here:
https://github.com/kmatch98/simpleTerminal

I'll work on the pye_mp updates and then try and figure out how to work github for a pull request.

**Comment by kmatch98** [comment]
Thanks for your help.  I just issued a pull request that includes the options for UART input and display output. [https://github.com/robert-hh/Micropython-Editor/pull/4](url) 

Let me know what you think.  I'm sure there are things that can be improved.

**Comment by robert-hh** [comment]
Thank you for the PR. Just a little note:
Do not apply changes pye_mp.py. This is a generated file. The master file is pye.py, and strip.sh creates various  variants out of it by using the cpp pre-processor. That would be the approach I would recommend for you. If you look into that file, you see lines like `#ifdef LINUX` and `#ifdef MICROPYTON`. Using that, you can enable or disable sections of code four this new environment. I used that approach to remove code that is not needed for specific environment. In addition, in each section there is something like `if is_linux`, to prevent execution of code in the wrong environment, if the full file is loaded.
I did not look into the changes yet. I'll do that later.

**Comment by kmatch98** [comment]
Ouch.  Didn’t realize that. 

I understand your approach and it makes a lot of sense.  I’ll see what it will take to merge it back into the original.

**Comment by kmatch98** [comment]
Just a follow up, I successfully verified the “modules” branch on another display type.

Hardware:
Adafruit ItsyBitsy NRF52840
320x240 display with driver chip ILI9341 via SPI

**Comment by robert-hh** [comment]
That's good. Does that combination use the same pye front-end?

**Comment by kmatch98** [comment]
I updated my comment to indicate that I was using pye_lcd.py and pye.py
