### ISSUE TITLE
RTC memory for clipboard/undo - enhancement

### ISSUE THREAD

**Issue by DG12** [robert-hh/Micropython-Editor#26]
Do all/most ESP32's (that you are familiar with and would run pye) have significant RTC (recovery) memory which could be used for clipboard or  undo stack?

**Comment by DG12** [comment]
My experiments show that even a soft reset ( REPL ^f ) reset the memory accessible via rtc.memory.
This would not present a problem for pye as clipboard or undo stack.

**Comment by robert-hh** [comment]
The `pye` code is identical for all MicroPython supported MCUs. That's one reason not to use the RTC memory for `pye`. The other is the limited size of the RTC memory and the fact, that this memory is NOT part of python's dynamic memory management, making it's use for `pye` hardly useful.

**Comment by DG12** [comment]
I hear you. I keep thinking . :-)

Any thoughts on [https://github.com/robert-hh/Micropython-Editor/issues/25](url)
